id: PF6E44BCA
initial_creation_type: ocr
source_metadata:
  volumes:
    44cbf01299ac428eaff163d790490571:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོ་ལ་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
